[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mc-data-wrapper"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025090305,<26"
modular = ">=25.6.0.dev2025090305,<26"
python = "==3.11"
